CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance NUMERIC(38, 2) NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE transactions (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              amount NUMERIC(38, 2) NOT NULL,
                              category VARCHAR(255),
                              description VARCHAR(255),
                              transaction_date TIMESTAMP(6) NOT NULL,
                              type VARCHAR(255) NOT NULL,
                              account_id BIGINT,
                              CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES accounts(id)
);
